.gitignore
Makefile
README.md
baremetal-fib.ld
baremetal-fib.s
baremetal-print.s
scripts/build-baremetal.sh
scripts/build-elf.sh
scripts/build-initrd.sh

- Added bare metal RISC-V assembly (no Linux, no stdlib, no C) bootable sample. Supports QEMU `sifive_u` target.
- Implemented basic printf() alternative in RISC-V assembly with the following types supported in formatting: %s, %c, %d, %i, %u, %x, %o, %p.
- Updated Makefile and README with new build targets.
- Made Makefile support prebuilt RISC-V  toolchain.
- Added initial support for standard SPIKE RISC-V simulator.

Bare metal QEMU compatible sample.

---

README.md
baremetal-fib.ld
baremetal-fib.s

- Moved GNUs build-id section after the readonly data.
- Fixed wording in comments and README, added a link to RISC-V toolchain.

Potential fix for bare metal sample crash on Linux

---

Makefile

These are slow, even when they end up doing nothing.

Don't rebuild linux and busybox each time

---

baremetal-hello.s

My toolchain does not recognize the fp alias for some reason, use the
synonym s0 instead.

Change fp to s0

---

Makefile
baremetal-hello.s

* Extracted timer setup into set_timer_for_current_hart function. Implemented 64bit unsigned addition for RV32.
* Multiple hardware threads are supported by treating mtimercmp as an array, each element corresponds to separate hart.
* Shorter pseudo-instructions CSRS, CSRSI and immediate when possible
* ONE_SECOND actually comes from sifive_clint.h setup.

32bit support for timer interrupt 

---

Makefile
baremetal-stub.s
baremetal-user.s

* Example sets up trap vectors and jumps to User mode.
* Simple syscall usage.
* Jump tables for interrupt, exception and syscall handling.
* Works with RISC-V 32 bit.
* 'make baremetal-user' to build and run

Example code to enter user mode

---

baremetal-user.s
baremetal.ld

* Setup Physical Memory Protection
* Align code and stack on 4KiB pages - it seems that QEMU tests access flags only once per page
* Use of constants to add clarity to code
qemu-system-riscv64 -nographic -machine sifive_u -bios none -kernel baremetal/user_sifive_u
Hello from M-mode!
Hello from U-mode!
Read user CSR: OK
Read from memory: OK
Read/write stack: OK
Read from unaligned memory:  OK
Illegal write to read-only memory: OK
Illegal read from protected CSR: Exception occured, mcause:0x2 mepc:0x80001114 mtval:0x0 (user payload at:0x80001000, stack top:0x80005000).
Illegal read from protected memory: Exception occured, mcause:0x5 mepc:0x80001130 mtval:0x80003000 (user payload at:0x80001000, stack top:0x80005000).
Done.

Memory protection

---

Makefile
src/baremetal-hello.s
src/baremetal-user.s
src/kernel.c
src/kernel.h
src/userland.c

Started moving kernel code to C. Added kernel-mode timer interrupt, which captures userland program counter, schedules itself for the next tick and returns to the user process at the point where it was interrupted.

Beginnings of a basic scheduler

---

src/boot.s
src/kernel.c

Unhardcode the expected fixed size of pointer, make it dependent on the
actual sizeof(p).
Also, fix a bug with stack handling in kprints and sys_puts. I was
misusing the sx/lx macros by specifying an offset in bytes to them instead
of an offset in registers. Use stackalloc_x/stackfree_x along with sx/lx
to symmetrically specify number of registers to both.

Fix warning in kprintp

---

Makefile
scripts/qemu-launcher.py

I want to run tests inside qemu, but that means it has to terminate
somehow. This script prepares the ground for this. It runs qemu from
within a Python script as a subprocess, taking complete control over
stdin and stdout, and process lifetime.
The test stdout+stderr will be captured in a file, which can then be
compared against expected output. The test running time can be capped by
a timeout.
As a side effect, intercepting stdin also allows the script to listen to
signals like Ctrl-c, which finally allows a convenient qemu termination
in dev environment.

Add a qemu launcher script for future tests and convenience

---

Makefile
include/kernel.h
include/pmp.h
include/riscv.h
src/boot.s
src/kernel.c
src/pmp.c
src/riscv.c

Also started moving low level RISC-V-specific functions and constants to
separate files. Later higher-level wrappers will emerge above them in
order to make C code less assembly-like and more readable.

Move memory protection init code to C

---

scripts/qemu-launcher.py

* qemu-launcher.py:11:0: W0611: Unused import time (unused-import)
* qemu-launcher.py:75:0: C0330: Wrong continued indentation (add 3 spaces).
* qemu-launcher.py:76:0: C0330: Wrong continued indentation.
* qemu-launcher.py:107:0: C0330: Wrong continued indentation (add 17 spaces).
* qemu-launcher.py:108:0: C0330: Wrong continued indentation (add 17 spaces).
* qemu-launcher.py:109:0: C0330: Wrong continued indentation.
I didn't fix:
* qemu-launcher.py:1:0: C0103: Module name "qemu-launcher" doesn't conform to snake_case naming style (invalid-name)
* qemu-launcher.py:39:23: W0613: Unused argument 'sig' (unused-argument)
* qemu-launcher.py:39:28: W0613: Unused argument 'frame' (unused-argument)

scripts/qemu-launcher.py: fixed linter warnings

---

.gitignore
Makefile
README.md
scripts/qemu-launcher.py

Running gdb is now super easy, just two commands:
make run-baremetal DBG=1    # just like before
make gdb                    # magic!
The magic is achieved by qemu-launcher, which knows enough to write a
.gdbinit file, which gdb picks up automatically, and when it does, it's
ready to start debugging right away.

Streamline running gdb

---

.github/workflows/maketest.yml
Makefile
include/fdt.h
include/kernel.h
include/proc.h
include/string.h
include/sys.h
scripts/qemu-launcher.py
src/boot.s
src/fdt.c
src/kernel.c
src/proc_test.c
src/string.c
testdata/want-output-u32.txt
testdata/want-output-u64.txt

This adds a rudimentary Flattened Device Tree reader, which allows us
accessing the command line parameters for kernel, passed via qemu's
`-append` flag.
This in turn allows specifying which test cases we want to run. This
commit adds the first such test case: a "dry run" kernel with no
userland processes.
Unfortunately, E machines don't seem to implement device trees, so no
way to run tests on them yet.

Implement parameter passing to kernel on unleashed machines

---

src/baremetal.ld
src/boot.s

Thank you for the great project at first!
I have a question here: For the .bss section, as far as I know, it will contain the area of memory used to hold static variables which must be initialized to zero. Although it may not be a big problem on the emulator(since the emulator could initialize the memory region to zero itself), I think it is still worth fixing it. Do we need to ensure the correctness by clearing the .bss section before ever calling any C codes? Or am I misunderstanding something for the question?

Clear the bss section before calling C codes

---

.github/workflows/maketest.yml

The tests based on qemu-launcher.py seem to be broken now, I'm disabling
them to avoid noise from Github actions.
Filed #43 to investigate further.

Disable broken integration tests

---

src/kernel.c

10628f9 has introduced a bug: our rudimentary scheduler now always
leaves one process out of the game. Fix the conditionals.

Fix bug in round-robin scheduler

---

src/boot.s

c2fbe93 has introduced zeroing out of bss section, which trashes a1
register, which contains the address of FDT header on boot. The fix is
trivial: replace a0/a1 with t0/t1.
The breakage should've been caught by Github actions, but they don't run
automatically for the first-time contributors, and that's how it went
unnoticed.

Fix build: parameter parsing via FDT got broken

---

src/kernel.c

Don't depend on a lookup table in a .data section. This function is
useful to debug things in cases where .data is wrongly mapped or not
initialized or otherwise unavailable.

Drop hex_table from kprintul()

---

Makefile
src/boot.s

Some flags have to be different for HiFive1-revB (at the very least,
ROM_START), and I suspect we will need to tweak more parameters.
The target doesn't work as such yet, but some parts of boot process
can be observed in stdout. On Linux, stdout can be observed with:
$ sudo stty -F /dev/ttyACM0 115200 igncr
$ sudo cat /dev/ttyACM0

Add a separate binary for hardware target

---

Makefile
src/boot.s

We used to use an atomic op, but that's unreliable while memory segments
are not init'ed: works fine on qemu, but will not work on physical
hardware.
This new approach avoids using main memory for synchronizing harts. It
hardcodes the 0th hart to be responsible for init'ing the memory
segments. Other harts spin a busy loop while the boot hart is done with
it. The harts communicate via MSIP register, which allows reliable
signalling between harts.
The approach is taken from the Freedom SDK CRT code.

Rewrite hart sync code during early boot

---

Makefile
include/kernel.h
include/machine/hifive1-revb.h
include/machine/qemu.h
src/boot.s
src/syscalls.c
src/userland.c

There were two major problems with our code on HiFive: wrong trap_vector
and wrong syscall_vector.
Trap vector had two problems of its own: first, on HiFive a vectored
trap vectored is required to be aligned to 64 bytes. Second, with
compact instructions the vector was too dense, so we need to align each
entry to 4 bytes as well. Did the same for exception_vector as well.
The problem with syscall vector was different: the global variable got
placed in a .data segment by default, as it should be. But we're still
missing code that copies .data segment from ROM to RAM, so in effect the
vector was garbage. As a quick fix I moved syscall_vector to .text, as
it's meant to be read-only anyway.
Finally, a couple minor fixes: moved the clock freq definition to
machine-specific headers, as they …

Make it run on HiFive1 Rev B

---

.github/workflows/maketest.yml
Makefile

The problem was the new GCC version building with Global Offset Table by
default, which was causing a NULL pointer dereference. This was
happening very early in FDT parsing code, where our normal trap vector
is not set up yet, so it was jumping to the early_trap_vector, which
deadloops.
Added `no-plt` and `no-pic` flags to address this.
Fixes #43.

Reenable integration tests

---

include/kernel.h
src/baremetal-print.s
src/boot.s
src/fdt.c
src/kernel.c
testdata/want-output-u32.txt
testdata/want-output-u64.txt

We already have `printf` implemented, but we needed a calling convention
adapter.
We no longer need `kprints`, `kprintp` and `kprintul`, so ditch them.

Implement proper kprintf, drop other half-assed helpers

---

Makefile
include/kernel.h
include/proc.h
include/riscv.h
src/kernel.c
src/proc.c
src/riscv.c

Incidentally, move some low-level RISC-V-specific code to riscv.c.

Cleanup: move more process-related code together

---

Makefile
scripts/qemu-launcher.py

And group all test_* targets at the end of makefile for easier
navigations between the targets.
Also disable scheduler-locking by default. It's indispensable when
debugging early boot code, but an annoying nuisance in all other cases.
So let's have it handy but commented out by default.

Add debug flags to all user_* targets

---

Makefile
include/kernel.h
include/proc.h
include/riscv.h
include/sys.h
src/boot.s
src/context.s
src/kernel.c
src/proc.c
src/proc_test.c
src/riscv.c
src/userland.c

Most significantly (for now), this allows each userland process to have
its own stack. The change in userland.c demonstrates that: we now call
`getpid()` once before the loop and store it in a stack variable.

Improve context switching: save all userland registers

---

Makefile
include/pagealloc.h
include/sys.h
src/baremetal.ld
src/kernel.c
src/pagealloc.c
testdata/want-output-u32.txt
testdata/want-output-u64.txt

Break all the memory above stack into pages and keep track of them. The
page table is fixed at 32 pages for now, as we're severely limited by the
small HiFive1 RAM size. This should not be a problem for quite a long
time, not until we try to run some actual userland programs.

Add paged memory allocations

---

src/usyscalls.s

In the syscalls code I was writing return address to the wrong offset,
thus trashing whatever was in that stack location. Looks like the bug
was lurking here for a year since the very first introduction of this
code, and surviving all modifications:
https://github.com/rtfb/riscv64-in-qemu/commit/83543b7fba82b51eb8198dfa6afcbf93ced69b4f
https://github.com/rtfb/riscv64-in-qemu/commit/279c3cceb85a4d5ea770fa03f92e0118f2f92cc6
https://github.com/rtfb/riscv64-in-qemu/commit/e7aa82a0dd3f2c0e204901f809ea232936e7c74c
Even more hilarious is that the bug didn't manifest itself for so long.
Our userland programs are so simple yet, using so little stack, that the
bug is not observable even now, I discovered it in WIP code working on
another syscall.

Fix an outrageous bug trashing the stack
